version: '3.7'

services:

  ignite_node_1:
    image: apacheignite/ignite:${ignite_version}
    hostname: ignite_node_1
    container_name: ignite_node_1
    volumes:
      - ./vm-ignite-config-test.xml:/config-file.xml
      - ../ignite-service/target/ignite-service-${project_version}.jar:/opt/ignite/apache-ignite/libs/rsc-index-ignite-${project_version}.jar
    environment:
      - CONFIG_URI=/config-file.xml
      - JVM_OPTS=-Xmx512m -Xms512m -server -XX:+AggressiveOpts -XX:+UseG1GC -XX:MaxPermSize=256m -XX:+DisableExplicitGC -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  ignite_node_2:
    image: apacheignite/ignite:${ignite_version}
    hostname: ignite_node_2
    container_name: ignite_node_2
    volumes:
      - ./vm-ignite-config-test.xml:/config-file.xml
      - ../ignite-service/target/ignite-service-${project_version}.jar:/opt/ignite/apache-ignite/libs/rsc-index-ignite-${project_version}.jar
    environment:
      - CONFIG_URI=/config-file.xml
      - JVM_OPTS=-Xmx512m -Xms512m  -server -XX:+AggressiveOpts -XX:+UseG1GC -XX:MaxPermSize=256m -XX:+DisableExplicitGC -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  ignite_benchmark:
    image: local-benchmark/jmh-ignite-benchmark:${project_version}
    hostname: ignite_benchmark
    container_name: ignite_benchmark
    depends_on:
      - ignite_node_1
      - ignite_node_2
    volumes:
      - ./vm-ignite-config-test.xml:/config-file.xml
    environment:
      - CONFIG_URI=/config-file.xml
      - JMH_PARAMS=-jvmArgs '-Djmh.shutdownTimeout=1' -jvmArgs '-Xmx1G' -jvmArgs '-Xms512m' -bm thrpt -wi 1 -t 1 -i 1 -f 1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1536M
